# Generated by Django 3.2.5 on 2021-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='%d/%m/%Y'),
        ),
    ]
