# Generated by Django 3.2.5 on 2021-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
